all: stripped1_prevnext_by_size.eps stripped2_prevnext_by_size.eps stripped3_prevnext_by_size.eps stripped4_prevnext_by_size.eps

stripped1_prevnext_by_size.eps: ../step1/stripped1
	./intervals.py ../step1/stripped1 ./stripped1

stripped2_prevnext_by_size.eps: ../step1/stripped2
	./intervals.py ../step1/stripped2 ./stripped2

stripped3_prevnext_by_size.eps: ../step1/stripped3
	./intervals.py ../step1/stripped3 ./stripped3

stripped4_prevnext_by_size.eps: ../step1/stripped4
	./intervals.py ../step1/stripped4 ./stripped4
