all: stripped1_inflow.eps stripped2_inflow.eps stripped3_inflow.eps stripped4_inflow.eps

stripped1_inflow.eps: ../step1/stripped1
	./inflow.py ../step1/stripped1 ./stripped1

stripped2_inflow.eps: ../step1/stripped2
	./inflow.py ../step1/stripped2 ./stripped2

stripped3_inflow.eps: ../step1/stripped3
	./inflow.py ../step1/stripped3 ./stripped3

stripped4_inflow.eps: ../step1/stripped4
	./inflow.py ../step1/stripped4 ./stripped4
